language: python
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: nosetests
sudo: false
after_success:
  - which expect
  - echo $DEPLOY_HOST_PUB >> ~/.ssh/known_hosts
  - eval "$(ssh-agent -s)"  # start the ssh agent
  - echo $DEPLOY_KEY > .travis_deploy_key.pem
  - chmod 600 .travis_deploy_key.pem
  - ./.travis_setup_key.sh
  - ssh-add -L
  - git remote add deploy dokku@${GLOBUS_DOKKU_IP}:auth_demo_prod
  - git push deploy
