swagger: '2.0'
info:
  title: Globus Auth API Explorer
  description: Globus Auth API
  version: "0.0.1"
host: globus_auth_proxy.pixelrave.com
paths:
  /token_details:
    get:
      summary: Token Details
      description: Get the token details
      parameters:
        - name: fields[token]
          in: query
          allowEmptyValue: false
          description: JSON API fields param
          type: string
          format: string
      responses:
        default:
          description: The response
  /identities:
    get:
      summary: Identities
      description: Get the identities
      responses:
        default:
          description: The response